'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Course_TYPED_IN
    Public Property course_id As String
    Public Property course As String
    Public Property credit As Nullable(Of Short)
    Public Property classroom As String
    Public Property schedule As String
    Public Property enrollment As Nullable(Of Integer)
    Public Property faculty_id As String

    Public Overridable Property Faculty_TYPED_IN As Faculty_TYPED_IN
    Public Overridable Property StudentCourse_TYPED_IN As ICollection(Of StudentCourse_TYPED_IN) = New HashSet(Of StudentCourse_TYPED_IN)

End Class
