'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Faculty_TYPED_IN
    Public Property faculty_id As String
    Public Property faculty_name As String
    Public Property office As String
    Public Property phone As String
    Public Property collage As String
    Public Property title As String
    Public Property email As String

    Public Overridable Property Course_TYPED_IN As ICollection(Of Course_TYPED_IN) = New HashSet(Of Course_TYPED_IN)
    Public Overridable Property LogIn_TYPED_IN As ICollection(Of LogIn_TYPED_IN) = New HashSet(Of LogIn_TYPED_IN)

End Class
