'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LogIn_TYPED_IN
    Public Property user_name As String
    Public Property pass_word As String
    Public Property faculty_id As String
    Public Property student_id As String

    Public Overridable Property Faculty_TYPED_IN As Faculty_TYPED_IN
    Public Overridable Property Student_TYPED_IN As Student_TYPED_IN

End Class
