'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentCourse_TYPED_IN
    Public Property s_course_id As Integer
    Public Property student_id As String
    Public Property course_id As String
    Public Property credit As Nullable(Of Integer)
    Public Property major As String

    Public Overridable Property Course_TYPED_IN As Course_TYPED_IN
    Public Overridable Property Student_TYPED_IN As Student_TYPED_IN

End Class
