'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student_TYPED_IN
    Public Property student_id As String
    Public Property student_name As String
    Public Property gpa As Nullable(Of Double)
    Public Property credits As Nullable(Of Integer)
    Public Property major As String
    Public Property schoolYear As String
    Public Property email As String

    Public Overridable Property LogIn_TYPED_IN As ICollection(Of LogIn_TYPED_IN) = New HashSet(Of LogIn_TYPED_IN)
    Public Overridable Property StudentCourse_TYPED_IN As ICollection(Of StudentCourse_TYPED_IN) = New HashSet(Of StudentCourse_TYPED_IN)

End Class
